name: argo_scuolanext
description: Applicazione non ufficiale per il registro elettronico argo

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  intl_translation: ^0.16.6
  flutter_launcher_icons: ^0.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path: assets/icons/launcher_icon.png
  android: true
  ios: true
