name: argo_scuolanext
description: unofficial argo's scuolanext application

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0
  shared_preferences: ^0.4.1

dev_dependencies:
  intl_translation: ^0.16.6
  flutter_launcher_icons: ^0.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_bw.png

flutter_icons:
  image_path: assets/icons/launcher_icon.png
  android: true
  ios: true
